name: generate github-profile-readme-snake.svg

on:
  schedule: # chạy theo lịch trình
    - cron: "0 0 * * *" # chạy mỗi 24 giờ lúc nửa đêm
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: HuynhKhanhDuy2912 # Thay thế bằng tên người dùng GitHub của bạn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=black # Bạn có thể tùy chỉnh màu sắc ở đây
            dist/github-contribution-grid-snake.gif?frame_rate=12&color_snake=purple&color_dots=pink
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
